/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedPersetujuanRouteImport } from './routes/_authenticated/persetujuan'
import { Route as AuthenticatedDraftRouteImport } from './routes/_authenticated/draft'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPetaniIndexRouteImport } from './routes/_authenticated/petani.index'
import { Route as AuthenticatedPembelianIndexRouteImport } from './routes/_authenticated/pembelian.index'
import { Route as AuthenticatedPelangganIndexRouteImport } from './routes/_authenticated/pelanggan.index'
import { Route as AuthenticatedPenjualanBaruRouteImport } from './routes/_authenticated/penjualan.baru'
import { Route as AuthenticatedPenjualanIdRouteImport } from './routes/_authenticated/penjualan.$id'
import { Route as AuthenticatedPembelianBaruRouteImport } from './routes/_authenticated/pembelian.baru'
import { Route as AuthenticatedPembelianIdRouteImport } from './routes/_authenticated/pembelian.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersetujuanRoute =
  AuthenticatedPersetujuanRouteImport.update({
    id: '/persetujuan',
    path: '/persetujuan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDraftRoute = AuthenticatedDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetaniIndexRoute =
  AuthenticatedPetaniIndexRouteImport.update({
    id: '/petani/',
    path: '/petani/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianIndexRoute =
  AuthenticatedPembelianIndexRouteImport.update({
    id: '/pembelian/',
    path: '/pembelian/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPelangganIndexRoute =
  AuthenticatedPelangganIndexRouteImport.update({
    id: '/pelanggan/',
    path: '/pelanggan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenjualanBaruRoute =
  AuthenticatedPenjualanBaruRouteImport.update({
    id: '/penjualan/baru',
    path: '/penjualan/baru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenjualanIdRoute =
  AuthenticatedPenjualanIdRouteImport.update({
    id: '/penjualan/$id',
    path: '/penjualan/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianBaruRoute =
  AuthenticatedPembelianBaruRouteImport.update({
    id: '/pembelian/baru',
    path: '/pembelian/baru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianIdRoute =
  AuthenticatedPembelianIdRouteImport.update({
    id: '/pembelian/$id',
    path: '/pembelian/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/draft': typeof AuthenticatedDraftRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/pelanggan/': typeof AuthenticatedPelangganIndexRoute
  '/pembelian/': typeof AuthenticatedPembelianIndexRoute
  '/petani/': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/draft': typeof AuthenticatedDraftRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/pelanggan': typeof AuthenticatedPelangganIndexRoute
  '/pembelian': typeof AuthenticatedPembelianIndexRoute
  '/petani': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/draft': typeof AuthenticatedDraftRoute
  '/_authenticated/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/_authenticated/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/_authenticated/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/_authenticated/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/_authenticated/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/_authenticated/pelanggan/': typeof AuthenticatedPelangganIndexRoute
  '/_authenticated/pembelian/': typeof AuthenticatedPembelianIndexRoute
  '/_authenticated/petani/': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/draft'
    | '/persetujuan'
    | '/riwayat'
    | '/pembelian/$id'
    | '/pembelian/baru'
    | '/penjualan/$id'
    | '/penjualan/baru'
    | '/pelanggan/'
    | '/pembelian/'
    | '/petani/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/draft'
    | '/persetujuan'
    | '/riwayat'
    | '/pembelian/$id'
    | '/pembelian/baru'
    | '/penjualan/$id'
    | '/penjualan/baru'
    | '/pelanggan'
    | '/pembelian'
    | '/petani'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/draft'
    | '/_authenticated/persetujuan'
    | '/_authenticated/riwayat'
    | '/_authenticated/pembelian/$id'
    | '/_authenticated/pembelian/baru'
    | '/_authenticated/penjualan/$id'
    | '/_authenticated/penjualan/baru'
    | '/_authenticated/pelanggan/'
    | '/_authenticated/pembelian/'
    | '/_authenticated/petani/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/persetujuan': {
      id: '/_authenticated/persetujuan'
      path: '/persetujuan'
      fullPath: '/persetujuan'
      preLoaderRoute: typeof AuthenticatedPersetujuanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/draft': {
      id: '/_authenticated/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof AuthenticatedDraftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/petani/': {
      id: '/_authenticated/petani/'
      path: '/petani'
      fullPath: '/petani/'
      preLoaderRoute: typeof AuthenticatedPetaniIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/': {
      id: '/_authenticated/pembelian/'
      path: '/pembelian'
      fullPath: '/pembelian/'
      preLoaderRoute: typeof AuthenticatedPembelianIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan/': {
      id: '/_authenticated/pelanggan/'
      path: '/pelanggan'
      fullPath: '/pelanggan/'
      preLoaderRoute: typeof AuthenticatedPelangganIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penjualan/baru': {
      id: '/_authenticated/penjualan/baru'
      path: '/penjualan/baru'
      fullPath: '/penjualan/baru'
      preLoaderRoute: typeof AuthenticatedPenjualanBaruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penjualan/$id': {
      id: '/_authenticated/penjualan/$id'
      path: '/penjualan/$id'
      fullPath: '/penjualan/$id'
      preLoaderRoute: typeof AuthenticatedPenjualanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/baru': {
      id: '/_authenticated/pembelian/baru'
      path: '/pembelian/baru'
      fullPath: '/pembelian/baru'
      preLoaderRoute: typeof AuthenticatedPembelianBaruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/$id': {
      id: '/_authenticated/pembelian/$id'
      path: '/pembelian/$id'
      fullPath: '/pembelian/$id'
      preLoaderRoute: typeof AuthenticatedPembelianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftRoute: typeof AuthenticatedDraftRoute
  AuthenticatedPersetujuanRoute: typeof AuthenticatedPersetujuanRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedPembelianIdRoute: typeof AuthenticatedPembelianIdRoute
  AuthenticatedPembelianBaruRoute: typeof AuthenticatedPembelianBaruRoute
  AuthenticatedPenjualanIdRoute: typeof AuthenticatedPenjualanIdRoute
  AuthenticatedPenjualanBaruRoute: typeof AuthenticatedPenjualanBaruRoute
  AuthenticatedPelangganIndexRoute: typeof AuthenticatedPelangganIndexRoute
  AuthenticatedPembelianIndexRoute: typeof AuthenticatedPembelianIndexRoute
  AuthenticatedPetaniIndexRoute: typeof AuthenticatedPetaniIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftRoute: AuthenticatedDraftRoute,
  AuthenticatedPersetujuanRoute: AuthenticatedPersetujuanRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedPembelianIdRoute: AuthenticatedPembelianIdRoute,
  AuthenticatedPembelianBaruRoute: AuthenticatedPembelianBaruRoute,
  AuthenticatedPenjualanIdRoute: AuthenticatedPenjualanIdRoute,
  AuthenticatedPenjualanBaruRoute: AuthenticatedPenjualanBaruRoute,
  AuthenticatedPelangganIndexRoute: AuthenticatedPelangganIndexRoute,
  AuthenticatedPembelianIndexRoute: AuthenticatedPembelianIndexRoute,
  AuthenticatedPetaniIndexRoute: AuthenticatedPetaniIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
