/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedLotRouteImport } from './routes/_authenticated/lot'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedKasRouteImport } from './routes/_authenticated/kas'
import { Route as AuthenticatedJenisIkanRouteImport } from './routes/_authenticated/jenis-ikan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBiayaRouteImport } from './routes/_authenticated/biaya'
import { Route as AuthenticatedAnalisisRouteImport } from './routes/_authenticated/analisis'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPetaniIndexRouteImport } from './routes/_authenticated/petani.index'
import { Route as AuthenticatedPembelianIndexRouteImport } from './routes/_authenticated/pembelian.index'
import { Route as AuthenticatedPelangganIndexRouteImport } from './routes/_authenticated/pelanggan.index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai.index'
import { Route as AuthenticatedPenjualanBaruRouteImport } from './routes/_authenticated/penjualan.baru'
import { Route as AuthenticatedPenjualanIdRouteImport } from './routes/_authenticated/penjualan.$id'
import { Route as AuthenticatedPembelianBaruRouteImport } from './routes/_authenticated/pembelian.baru'
import { Route as AuthenticatedPembelianIdRouteImport } from './routes/_authenticated/pembelian.$id'
import { Route as AuthenticatedAiThreadIdRouteImport } from './routes/_authenticated/ai.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLotRoute = AuthenticatedLotRouteImport.update({
  id: '/lot',
  path: '/lot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasRoute = AuthenticatedKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJenisIkanRoute = AuthenticatedJenisIkanRouteImport.update({
  id: '/jenis-ikan',
  path: '/jenis-ikan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiayaRoute = AuthenticatedBiayaRouteImport.update({
  id: '/biaya',
  path: '/biaya',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalisisRoute = AuthenticatedAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPetaniIndexRoute =
  AuthenticatedPetaniIndexRouteImport.update({
    id: '/petani/',
    path: '/petani/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianIndexRoute =
  AuthenticatedPembelianIndexRouteImport.update({
    id: '/pembelian/',
    path: '/pembelian/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPelangganIndexRoute =
  AuthenticatedPelangganIndexRouteImport.update({
    id: '/pelanggan/',
    path: '/pelanggan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenjualanBaruRoute =
  AuthenticatedPenjualanBaruRouteImport.update({
    id: '/penjualan/baru',
    path: '/penjualan/baru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenjualanIdRoute =
  AuthenticatedPenjualanIdRouteImport.update({
    id: '/penjualan/$id',
    path: '/penjualan/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianBaruRoute =
  AuthenticatedPembelianBaruRouteImport.update({
    id: '/pembelian/baru',
    path: '/pembelian/baru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembelianIdRoute =
  AuthenticatedPembelianIdRouteImport.update({
    id: '/pembelian/$id',
    path: '/pembelian/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiThreadIdRoute = AuthenticatedAiThreadIdRouteImport.update({
  id: '/ai/$threadId',
  path: '/ai/$threadId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/biaya': typeof AuthenticatedBiayaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jenis-ikan': typeof AuthenticatedJenisIkanRoute
  '/kas': typeof AuthenticatedKasRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/lot': typeof AuthenticatedLotRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/pelanggan/': typeof AuthenticatedPelangganIndexRoute
  '/pembelian/': typeof AuthenticatedPembelianIndexRoute
  '/petani/': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/biaya': typeof AuthenticatedBiayaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jenis-ikan': typeof AuthenticatedJenisIkanRoute
  '/kas': typeof AuthenticatedKasRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/lot': typeof AuthenticatedLotRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/pelanggan': typeof AuthenticatedPelangganIndexRoute
  '/pembelian': typeof AuthenticatedPembelianIndexRoute
  '/petani': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analisis': typeof AuthenticatedAnalisisRoute
  '/_authenticated/biaya': typeof AuthenticatedBiayaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jenis-ikan': typeof AuthenticatedJenisIkanRoute
  '/_authenticated/kas': typeof AuthenticatedKasRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/lot': typeof AuthenticatedLotRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/_authenticated/pembelian/$id': typeof AuthenticatedPembelianIdRoute
  '/_authenticated/pembelian/baru': typeof AuthenticatedPembelianBaruRoute
  '/_authenticated/penjualan/$id': typeof AuthenticatedPenjualanIdRoute
  '/_authenticated/penjualan/baru': typeof AuthenticatedPenjualanBaruRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/pelanggan/': typeof AuthenticatedPelangganIndexRoute
  '/_authenticated/pembelian/': typeof AuthenticatedPembelianIndexRoute
  '/_authenticated/petani/': typeof AuthenticatedPetaniIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analisis'
    | '/biaya'
    | '/dashboard'
    | '/jenis-ikan'
    | '/kas'
    | '/laporan'
    | '/lot'
    | '/pengaturan'
    | '/riwayat'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ai/$threadId'
    | '/pembelian/$id'
    | '/pembelian/baru'
    | '/penjualan/$id'
    | '/penjualan/baru'
    | '/ai/'
    | '/pelanggan/'
    | '/pembelian/'
    | '/petani/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analisis'
    | '/biaya'
    | '/dashboard'
    | '/jenis-ikan'
    | '/kas'
    | '/laporan'
    | '/lot'
    | '/pengaturan'
    | '/riwayat'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ai/$threadId'
    | '/pembelian/$id'
    | '/pembelian/baru'
    | '/penjualan/$id'
    | '/penjualan/baru'
    | '/ai'
    | '/pelanggan'
    | '/pembelian'
    | '/petani'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analisis'
    | '/_authenticated/biaya'
    | '/_authenticated/dashboard'
    | '/_authenticated/jenis-ikan'
    | '/_authenticated/kas'
    | '/_authenticated/laporan'
    | '/_authenticated/lot'
    | '/_authenticated/pengaturan'
    | '/_authenticated/riwayat'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/ai/$threadId'
    | '/_authenticated/pembelian/$id'
    | '/_authenticated/pembelian/baru'
    | '/_authenticated/penjualan/$id'
    | '/_authenticated/penjualan/baru'
    | '/_authenticated/ai/'
    | '/_authenticated/pelanggan/'
    | '/_authenticated/pembelian/'
    | '/_authenticated/petani/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lot': {
      id: '/_authenticated/lot'
      path: '/lot'
      fullPath: '/lot'
      preLoaderRoute: typeof AuthenticatedLotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas': {
      id: '/_authenticated/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof AuthenticatedKasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jenis-ikan': {
      id: '/_authenticated/jenis-ikan'
      path: '/jenis-ikan'
      fullPath: '/jenis-ikan'
      preLoaderRoute: typeof AuthenticatedJenisIkanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biaya': {
      id: '/_authenticated/biaya'
      path: '/biaya'
      fullPath: '/biaya'
      preLoaderRoute: typeof AuthenticatedBiayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analisis': {
      id: '/_authenticated/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AuthenticatedAnalisisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/petani/': {
      id: '/_authenticated/petani/'
      path: '/petani'
      fullPath: '/petani/'
      preLoaderRoute: typeof AuthenticatedPetaniIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/': {
      id: '/_authenticated/pembelian/'
      path: '/pembelian'
      fullPath: '/pembelian/'
      preLoaderRoute: typeof AuthenticatedPembelianIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan/': {
      id: '/_authenticated/pelanggan/'
      path: '/pelanggan'
      fullPath: '/pelanggan/'
      preLoaderRoute: typeof AuthenticatedPelangganIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penjualan/baru': {
      id: '/_authenticated/penjualan/baru'
      path: '/penjualan/baru'
      fullPath: '/penjualan/baru'
      preLoaderRoute: typeof AuthenticatedPenjualanBaruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penjualan/$id': {
      id: '/_authenticated/penjualan/$id'
      path: '/penjualan/$id'
      fullPath: '/penjualan/$id'
      preLoaderRoute: typeof AuthenticatedPenjualanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/baru': {
      id: '/_authenticated/pembelian/baru'
      path: '/pembelian/baru'
      fullPath: '/pembelian/baru'
      preLoaderRoute: typeof AuthenticatedPembelianBaruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembelian/$id': {
      id: '/_authenticated/pembelian/$id'
      path: '/pembelian/$id'
      fullPath: '/pembelian/$id'
      preLoaderRoute: typeof AuthenticatedPembelianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/$threadId': {
      id: '/_authenticated/ai/$threadId'
      path: '/ai/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AuthenticatedAiThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisisRoute: typeof AuthenticatedAnalisisRoute
  AuthenticatedBiayaRoute: typeof AuthenticatedBiayaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJenisIkanRoute: typeof AuthenticatedJenisIkanRoute
  AuthenticatedKasRoute: typeof AuthenticatedKasRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedLotRoute: typeof AuthenticatedLotRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedAiThreadIdRoute: typeof AuthenticatedAiThreadIdRoute
  AuthenticatedPembelianIdRoute: typeof AuthenticatedPembelianIdRoute
  AuthenticatedPembelianBaruRoute: typeof AuthenticatedPembelianBaruRoute
  AuthenticatedPenjualanIdRoute: typeof AuthenticatedPenjualanIdRoute
  AuthenticatedPenjualanBaruRoute: typeof AuthenticatedPenjualanBaruRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedPelangganIndexRoute: typeof AuthenticatedPelangganIndexRoute
  AuthenticatedPembelianIndexRoute: typeof AuthenticatedPembelianIndexRoute
  AuthenticatedPetaniIndexRoute: typeof AuthenticatedPetaniIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisisRoute: AuthenticatedAnalisisRoute,
  AuthenticatedBiayaRoute: AuthenticatedBiayaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJenisIkanRoute: AuthenticatedJenisIkanRoute,
  AuthenticatedKasRoute: AuthenticatedKasRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedLotRoute: AuthenticatedLotRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedAiThreadIdRoute: AuthenticatedAiThreadIdRoute,
  AuthenticatedPembelianIdRoute: AuthenticatedPembelianIdRoute,
  AuthenticatedPembelianBaruRoute: AuthenticatedPembelianBaruRoute,
  AuthenticatedPenjualanIdRoute: AuthenticatedPenjualanIdRoute,
  AuthenticatedPenjualanBaruRoute: AuthenticatedPenjualanBaruRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedPelangganIndexRoute: AuthenticatedPelangganIndexRoute,
  AuthenticatedPembelianIndexRoute: AuthenticatedPembelianIndexRoute,
  AuthenticatedPetaniIndexRoute: AuthenticatedPetaniIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
